tpm.c
tpm.h

According to TCG EFI Protocol Specification for TPM 2.0 family,
all events generated after the invocation of EFI_TCG2_GET_EVENT_LOG
shall be stored in an instance of an EFI_CONFIGURATION_TABLE aka
EFI TCG 2.0 final events table. Hence, it is necessary to trigger the
internal switch through calling get_event_log() in order to allow
to retrieve the logs from OS runtime.
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>

shim: trigger to record further logs to tcg 2.0 final event log area

---

Cryptlib/Makefile
Cryptlib/OpenSSL/Makefile
Makefile
lib/Makefile

This lets you do:
mkdir build-x64 build-ia32
cd build-x64
make TOPDIR=.. -f ../Makefile
cd ../build-ia32
setarch i686 -B make ARCH=ia32 TOPDIR=.. -f ../Makefile
And not worry about generated sources and headers mixing and matching.

Make it possible to build in a subdirectory.

---

Cryptlib/Makefile
Cryptlib/OpenSSL/Makefile
Makefile

Add -m64 compiler flag to allow cross-compiling to 64-bit version on 32-bit system
Signed-off-by: Tamas K Lengyel <lengyelt@ainfosec.com>

Allow compiling 64-bit version on 32-bit host

---

httpboot.c

We previously always set the gateway for IPv4 but it's not necessary. To improve the compatibility, when the default IPv4 gateway is empty, we just ignore it, or ip4cfg2->SetData() may return EFI_INVALID_PARAMETER. Besides, more error messages were added to help the user to identify the problem.

Improve HTTPBoot compatibility and print more error messages

---

shim.h

There are typos in the default DEBUGDIR.

Fix typo in debug path in shim.h

---

MokManager.c

When writing MokList with EFI_VARIABLE_APPEND_WRITE, some HP laptops
may just return EFI_SUCCESS without writing the content into the flash,
so we have no way to detect if MokList is updated or not. Now we always
read MokList first and write it back with the new content.
https://github.com/rhboot/shim/issues/105

MokManager: Stop using EFI_VARIABLE_APPEND_WRITE

---

Makefile

In Ubuntu 14.04, the following code in old Makefile:
mkdir -p Cryptlib/{Hash,Hmac,Cipher,Rand,Pk,Pem,SysCall}
will create a directory named "{Hash,Hmac,Cipher,Rand,Pk,Pem,SysCall}".
Signed-off-by: Ming Tan <ming.tan@intel.com>

Fix the compile error of mkdir wrong directory.

---

mok.c

Currently the CI [is failing](https://travis-ci.org/rhboot/shim/builds/487111376) because 29c11483101b460869a5e0dba1f425073862127d introduced an unmatched opening brace.
Closes #168

Fix build failure due to missing closing brace

---

errlog.c

VLogError() calculates the size of format strings by using calls to
SPrint and VSPrint with a StrSize of 0 and NULL for an output buffer.
Unfortunately, this is an incorrect usage of (V)Sprint. A StrSize
of "0" is special-cased to mean "there is no limit". So, we end up
writing our string to address 0x0. This was discovered because it
causes a crash on ARM where, unlike x86, it does not necessarily
have memory mapped at 0x0.
Replace the (V)SPrint calls with (V)PoolPrint calls, and we can use
StrLen() to calculate the size. Downside is that PoolPrint will
allocate pool memory to do this, so we need to release it.
Fixes: 25f6fd08cd26 ("try to show errors more usefully.")
Signed-off-by: dann frazier <dann.frazier@canonical.com>

VLogError(): Avoid NULL pointer dereferences in (V)SPrint calls

---

src/netboot.c

Some mainboards do not update the ProxyOffset dhcp information when using
proxy dhcp and boot menus.
This adds a fallback to check the PxeReply field if no boot information is
found in the v4 dhcp or proxy dhcp information

Check PxeReplyReceived as fallback in netboot

---

README.md

One of the really great things about Github IMO is how
"front and center" the README file in a repository is (just
compare with Sourceforge).
Github renders it more nicely if the file is declared to be Markdown,
so let's do that.  Add a bit of formatting: using code fences
for code, hyperlinks for other files etc.
I also added a title block from the Fedora package `Summary`
since while I know in theory shim is independent of bootloaders,
let's say what the 95% case is here.

Convert README -> README.md

---

src/shim.c

The DEFAULT_LOADER is a UCS-2 string and the StrLen() function returns the
number of UCS-2 encoded characters in the string. But the allocated memory
is in bytes, so only half of the needed memory to store it is allocated.
This leads to a buffer overrun when the StrCpy() function attempts to copy
the DEFAULT_LOADER to the allocated buffer.
Fixes: 354bd9b1931 ("Actually check for errors from set_second_stage()")
Reported-by: Stuart Hayes <stuart_hayes@dell.com>
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

Fix buffer overrun due DEFAULT_LOADER length miscalculation

---

include/defaults.mk

The previous make target was passing all of the target's prerequisites
as boot images to sbsign, causing it to fail.

Fix sbsign command usage

---

include/defaults.mk

Shim currently fails to build with these errors when DEFAULT_LOADER isn't provided:
.././src/shim.c: In function ‘set_second_stage’:
.././src/shim.c:2099:28: error: unknown escape sequence: '\g' [-Werror]
2099 |  second_stage_len = StrLen(DEFAULT_LOADER) + 1;
|                            ^~~~~~~~~~~~~~
.././src/shim.c:2105:23: error: unknown escape sequence: '\g' [-Werror]
2105 |  StrCpy(second_stage, DEFAULT_LOADER);
|                       ^~~~~~~~~~~~~~
.././src/netboot.c: In function ‘extract_tftp_info’:
.././src/netboot.c:192:24: error: unknown escape sequence: '\g' [-Werror]
192 |  CHAR8 template[sizeof DEFAULT_LOADER_CHAR];
|                        ^~~~~~~~~~~~~~~~~~~
.././src/netboot.c:194:30: error: unknown escape sequence: '\g' [-Werror]
194 |  translate_slashes(template, …

Fix escaping of DEFAULT_LOADER

---

.github/workflows/pullrequest.yml

This series of patches does two things:
- it re-works the PR CI builder so all the test targets use the same build steps
- it adds the sbat branch to the list of branches to build PRs against.

SBAT pull-request CI builds

---

Make.defaults
Makefile
data/sbat.csv
elf_aarch64_efi.lds
elf_arm_efi.lds
elf_ia32_efi.lds
elf_ia64_efi.lds
elf_x86_64_efi.lds

The Secure Boot Advanced Targeting (SBAT) [0] is a Generation Number Based
Revocation mechanism that is meant to replace the DBX revocation file list.
Binaries must contain a .sbat data section that has a set entries, each of
them consisting of UTF-8 strings as comma separated values. Allow to embed
this information into the fwupd EFI binary at build time.
The SBAT metadata must contain at least two entries. One that defines the
SBAT version used and another one that defines the component generation.
Downstream users can add additional entries if have changes that make them
diverge from the upstream code and potentially add other vulnerabilities.
The reason why an intermediate step is needed, is because the objcopy tool
only has support for pei-x86_64 and pei-i386 targets. So the .sbat …

Add a .sbat section to EFI binaries

---

.gitignore
BUILDING
Make.defaults
Make.rules
Makefile
elf_aarch64_efi.lds
elf_arm_efi.lds
elf_ia32_efi.lds
elf_ia64_efi.lds
elf_x86_64_efi.lds

In cases where we accept vendor shim binaries with additional patches,
it may become necessary to identify those builds with additional SBAT
data.  When we consider such patches, we should be proactive in asking
vendors to include that data in the .sbat sections of their trusted EFI
binaries.
This patch adds any data in data/sbat.*.csv (after a quick sanitizing
pass) after data/sbat.csv in the .sbat section, so  that no changes to
the upstream data/sbat.csv are ever required.

efi bins: add an easy way for vendors to add .sbat data

---

lib/variables.c

Sometimes we're loading structures that are parsed in string-like ways,
but can't necessarily be trusted to be zero-terminated.  Solve that by
making sure we always have enough aligned, trailing zero bytes to always
have at least one NUL character, no matter which character type is being
parsed.

get_variable: always allocate a NUL character at the end.

---

include/str.h

I wrote a test case for strnlena() and strndupa() and of course both
were off by one in the opposite directions... Woops.
I manually checked all the callers (including all the callers of strcata) and it looks like they should all handle this gracefully either way, but still, better to be correct.

Fix an off by one in strnlena()

---

Make.defaults

Not all distributions put the crt0-efi-$(ARCH).o file under
$LIB_DIR/gnuefi, some stash it directly in $LIB_DIR.  In an effort
to make the build a bit more user friendly, check if $LIB_DIR/gnuefi
exits before setting $EFI_PATH to that value; if $LIB_DIR/gnuefi does
not exist, fallback to $LIB_DIR for $EFI_PATH.

BUG: add some basic $EFI_PATH checking

---

Make.coverity

Not everybody uses bash as /bin/sh, and the scripting here is safe
just using single brackets.
Signed-off-by: Steve McIntyre <93sam@debian.org>

Fix bashisms in Make.coverity

---

sbat.c

This commit fixes the following gcc warnings for casting and
uninitialized variable.
sbat.c: In function 'verify_single_entry':
sbat.c:157:13: error: pointer targets in passing argument 1 of 'strcmp' differ in signedness [-Werror=pointer-sign]
if (strcmp(entry->component_name, sbat_var_entry->component_name) == 0) {
^~~~~
In file included from Cryptlib/Include/string.h:15:0,
from sbat.c:7:
Cryptlib/Include/OpenSslSupport.h:299:16: note: expected 'const char *' but argument is of type 'const CHAR8 * {aka const unsigned char *}'
int            strcmp      (const char *, const char *);
^~~~~~
sbat.c:157:36: error: pointer targets in passing argument 2 of 'strcmp' differ in signedness [-Werror=pointer-sign]
if (strcmp(entry->component_name, sbat_var_entry->component_name) == 0) { …

sbat: fix the gcc warnings

---

SBAT.md
data/sbat.csv

Two places we missed still have 0 for an sbat version - one doc and one
in our data csv.
This fixes those.

Fix two errant 'shim,0' outdated sbat cases.

---

include/sbat.h
pe.c

Replace the resource section with SBAT section.

sbat: fix the residual "resource section" for SBAT

---

SBAT.md

The raw text of the SBAT.md file is a bit of a mess, this patch
attempts to introduce some consistentcy to the text without affecting
the rendered Markdown.
The only content change was the addition of a missing period ('.') at
the end of sentence/paragraph; all of the other changes were purely
formatting changes.

SBAT: update the raw Markdown to look less terrible

---

pe.c

The current code rejects the .sbat section if the VirtualSize and
SizeOfRawData fields of the section header aren't the same, but this
is too strict. The VirtualSize corresponds to the size of the SBAT
metadata and isn't necessarily a multiple of the file alignment.
The on-disk size (SizeOfRawData) is a multiple of the file alignment
and is zero padded. Make sure that the on-disk size is at least as
large as virtual size, and ignore the .sbat section if it isn't.
This should fix https://github.com/rhboot/shim/issues/281.
Signed-off-by: Chris Coulson <chris.coulson@canonical.com>

sbat: Don't assume VirtualSize == SizeOfRawData

---

sbat.c

Fix a typo that inverted the check that validates that a CSV
column is not empty.
Signed-off-by: Thomas Frauendorfer | Miray Software <tf@miray.de>

Fix column size check in SBAT variable parsing.

---

replacements.c
shim.c
shim.h

When grub2 invoked Exit() in AArch64 AAVMF, the VM crashed with the
following messsages:
Unloading driver at 0x000B7D7B000
Synchronous Exception at 0x00000000BF5D5E68
AllocatePool: failed to allocate 800 bytes
Synchronous Exception at 0x00000000BF5D5E68
The similar error also showed when I modified MokManager to call
gBS->Exit() at the end of efi_main(). However, if MokManager just
returned, the error never showed. One significant difference is
whether the loaded image was restored or not, and the firmware seems
to need the original ImageBase pointer to do clean-up.
To avoid the potential crash, this commit adds restore_loaded_image() so
that we can restore the loaded image both in start_image() and
do_exit().

Restore loaded image of shim at Exit()

---

include/variables.h
lib/variables.c

This get_variable_size() implementation success in either of two cases:
- EFI_SUCCESS with *lenp == 0 if the variable isn't found
- EFI_SUCCESS with *lenp > 0 on success
In the event of other errors, it returns them to you.
There's nothing particularly interesting about the set_variable()
implementation here.

Add get_variable_size() and set_variable() wrappers.

---

.gitignore
Make.defaults

If the file Make.local exists, use it as a source of local build
configuration by including it in Make.defaults.

RFE: load local build configuration from Make.local if present

---

shim.c

"So, load options are a giant pain in the ass." - Peter Jones
This patch attempts to workaround two LoadOption problems seen on
my test system: arguments separated with only whitespace (L" ") and
strings that aren't properly NULL terminated.
In addition to my test system, it appears at least one other person
has run into a similar problem:
* https://github.com/rhboot/shim/issues/181

BUG: attempt to improve the argument handling

---

test-str.c

Steve McIntyre reports:
<Sledge> yay, arm64 string test fail
<Sledge> testing gnuefi_signed_strncmp
<Sledge> test_strncmp:713:got 128, expected < 0
<Sledge> test_strncmp:713:Assertion `(gnuefi_signed_strncmp("sbat\314\234\014,", "sbat\314\034\014,", 9)) >= 0' failed.
<Sledge> gnuefi_signed_strncmp failed
<Sledge> looking at that code, this is a test to check how broken the gnuefi strncmp is, yes?
<Sledge> and we're not actually using this implementation in shim AFAICS?
That is a correct understanding, and as such this patch just removes
that test from running on Arm platforms, where it is still too broken to
even do this much.

Nerf an unnecessary string test on arm.

---

Make.defaults
Makefile

We need to be using our patched version of gnu-efi
Signed-off-by: Steve McIntyre <93sam@debian.org>

Stop using EFI_PATH, and error out if people try to use it

---

include/system/stdarg.h

Don't check SHIM_UNIT_TEST.
This fixes conflicting declarations for __builtin_ms_va_list on amd64:
In file included from shim.h:47,
from test.c:10:
../include/system/stdarg.h:30:27: error: conflicting types for '__builtin_ms_va_list'
typedef __builtin_va_list __builtin_ms_va_list;
^~~~~~~~~~~~~~~~~~~~
cc1: note: previous declaration of '__builtin_ms_va_list' was here
In file included from shim.h:47,
from test-csv.c:9:
../include/system/stdarg.h:30:27: error: conflicting types for '__builtin_ms_va_list'
typedef __builtin_va_list __builtin_ms_va_list;
^~~~~~~~~~~~~~~~~~~~
cc1: note: previous declaration of '__builtin_ms_va_list' was here
In file included from shim.h:47,
from csv.c:6:
../include/system/stdarg.h:30:27: error: conflicting types for '__builtin_ms_va_list'
typedef …

Fix up build of test code using gcc 8

---

elf_aarch64_efi.lds
elf_arm_efi.lds

This fixes the SizeOfImage and SizeOfInitializedData headers on arm and
aa64.

arm and aarch64: fix some PE headers.

---

.gitignore
Make.defaults

If the file Make.local exists, use it as a source of local build
configuration by including it in Make.defaults.
(cherry picked from commit 57e38a1ebf73 in the shim-15.2 branch)

RFE: cherry pick Make.local from shim-15.2 to shim-15.3

---

lib/Makefile

The order in which the foreach() returns files differes from
Debian on WSL1 and Debian running natively.
When shim is build on these two platforms the resulting binaries differ.
This patch manually sorts the input file list to create identical binaries.
Signed-off-by: Thomas Frauendorfer | Miray Software <tf@miray.de>

Sort input file names in lib/Makefile

---

elf_aarch64_efi.lds
elf_arm_efi.lds

Similar to x86_64, the .sbat section is aligned to 4096, so we should
include the aligned part in SizeOfRawData as objcopy does for x86_64.
For VirtualSize, _sbat_vsize is used to reflect the actually size of
sbat.
This also fixes a strange hash mismatching in openSUSE build service
when attaching signature to AArch64 EFI images from shim package.

arm and aarch64: include the aligned part in SizeOfRawData of sbat

---

shim.c

If the LoadOptions string count is zero, then it's assumed that it is an
EFI_LOAD_OPTION and the OptionalData field attempt to be parsed. If that
fails as well, in the second stage was set to the default loader path.
But this behaviour was changed by the commit 018b74d2 ("shim: attempt to
improve the argument handling"), and not in that case the LoadOptions is
attempted to be used as a single string. This breaks some firmwares that
return something in the LoadOptions but are not a proper EFI device path.
Instead of making assumptions about the LoadOptions if can't be parsed
correctly, just use the default loader as it was done before that commit.
Reported-by: Thomas Frauendorfer | Miray Software <tf@miray.de>
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

shim: Use the default loader if an EFI_LOAD_OPTION can't be parsed

---

include/variables.h
lib/variables.c
mok.c

The MOK variable mirroring makes use of variable_create_esl, which
can only create a well-formed EFI_SIGNATURE_LIST containing a single
signature. Fix fill_esl and variable_create_esl to support creating
a EFI_SIGNATURE_LIST with one or more supplied EFI_SIGNATURE_DATA
structures.
Introduce variable_create_esl_with_one_signature and
fill_esl_with_one_signature for code that does want to create a
EFI_SIGNATURE_LIST containing a single signature constructed from
a supplied signature data buffer and owner GUID.

Ensure that MOK variable mirroring creates well formed ESLs

---

mok.c

If the bootservices MOK payload fits in to a single volatile
runtime variable, don't create additional mirrored variables in
the second pass of mirror_mok_db().

Avoid creating unnecessary mirrored MOK variables

---

lib/variables.c
mok.c

There are multiple issues in the MOK variable mirroring code due
to volatile variable size constraints, which all result in boot
failures:
- If a signature is encountered which doesn't fit in to a single
variable, the code enters an infinite loop because the cursor
isn't advanced in mirror_mok_db() after the call to
mirror_one_esl().
- If an ESL is encountered which doesn't fit in to a single
variable, it looks like the intention is for the ESL to be split
across multiple variables. However, mirror_one_esl() will write
the maximum variable size on each call, regardless of how much
data is remaining for the current ESL. If the size of a ESL isn't
a multiple of the maximum variable size, the final call to
mirror_one_esl() will append data from the start of the next
ESL and the cursor in …

Fix boot failures due to variable size constraints

---

elf_aarch64_efi.lds
elf_arm_efi.lds

xnox reports that with some versions of sbsign/sbcheck, it gets very
unhappy with non-contiguous sections and gaps between sections, which we
currently produce on targets with hand-coded headers.  This is all wrong
behavior from sbsigntools, and has been fixed in newer versions, but
nevertheless it's not hard for us to avoid.
This patch re-arranges the sections so there are no gaps, by padding the
file-size of .data and .sbat up to the full page, moving .sbat to be
before .vendor_cert, and moving .vendor_cert and .rela out of the range
covered by _edata, while still leaving included in the calculation of
SizeOfInitializedData.

arm/aa64: Swizzle some sections to make old sbsign happier.

---

.github/workflows/pullrequest.yml
Make.defaults
Makefile
lib/Makefile

This also makes the cross-build targets (and not the others) /use/ this
functionality, so we'll catch it if we break it again.
This fixes issue #340.

Make building outside of the top directory work.

---

Makefile

If no TOPDIR is defined and a vendor sbat CSV is placed in
$(BUILDDIR)/data/sbat.*.csv, objcopy fails with the following
error.
objcopy --add-section .sbat=/shim/data/sbat.csv \
--set-section-flags .sbat=contents,alloc,load,readonly,data \
sbat_data.o
objcopy --add-section ".sbat.microsoft=sbat.microsoft.csv" sbat_data.o
objcopy --add-section ".sbat.microsoft=sbat.microsoft.csv" sbat_data.o
objcopy:stuf2iKG: can't add section '.sbat.microsoft': bad value
make: *** [Makefile:120: sbat_data.o] Error 1
The sbat.vendor.csv is getting included twice in VENDOR_SBATS.
Use sort to ensure unique entries in VENDOR_SBATS
Signed-off-by: Chris Co <chrco@microsoft.com>

Makefile: sort vendor sbats to remove duplicates

---

mok.c

Linux kernel is picky when reserving the memory for x86 and it only
expects BootServicesData:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/platform/efi/quirks.c?h=v5.11#n254
Otherwise, the following error would show during system boot:
Apr 07 12:31:56.743925 localhost kernel: efi: Failed to lookup EFI memory descriptor for 0x000000003dcf8000
Although BootServicesData would be reclaimed after ExitBootService(),
linux kernel reserves MOK config table when it detects the existence of
the table, so it's fine to allocate the table as BootServicesData.

mok: allocate MOK config table as BootServicesData

---

mok.c

The EFI 1.10 spec (and presumably earlier revisions as well) didn't have
RT->QueryVariableInfo(), and on Chris Murphy's MacBookPro8,2 , that
memory appears to be initialized randomly.
This patch changes it to not call RT->QueryVariableInfo() if the
EFI_RUNTIME_SERVICES table's major revision is less than two, and
assumes our maximum variable size is 1024 in that case.

Don't call QueryVariableInfo() on EFI 1.10 machines

---

shim.c

An openSUSE user reported(*) that shim 15.4 failed to boot the system
with the following message:
"Could not create MokListXRT: Out of Resources"
In the beginning, I thought it's caused by the growing size of
vendor-dbx. However, we found the following messages after set
SHIM_VERBOSE:
max_var_sz:8000 remaining_sz:85EC max_storage_sz:9000
SetVariable(“MokListXRT”, ... varsz=0x1404) = Out of Resources
Even though the firmware claimed the remaining storage size is 0x85EC
and the maximum variable size is 0x8000, it still rejected MokListXRT
with size 0x1404. It seems that the return values from QueryVariableInfo()
are not reliable. Since this firmware didn't really support Secure Boot,
the variable mirroring is not so critical, so we can just accept the
failure of import_mok_state() and …

Relax the check for import_mok_state()

---

include/ucs2.h
pe.c
shim.c

The load options handling is quite complicated and tries to accomodate
several scenarios, but there are currently multiple issues:
- If the supplied LoadOptions is an EFI_LOAD_OPTION structure,
second_stage gets initialized to the entire contents of the OptionalData
field and load_options is initialized to NULL, which means it isn't
possible to pass additional options to the second stage loader (and it
looks like the intention is for this to be supported).
- If the supplied LoadOptions contains 2 or more strings, the code seems
to assume that shim was executed from the UEFI shell and that the first
argument is the path of the shim executable, so it's ignored. But this
breaks the ability to pass additional options to the second stage loader
from BDS on firmware implementations that …

shim: another attempt to fix load options handling

---

Makefile
elf_aarch64_efi.lds
elf_arm_efi.lds

The previous commit(*) merged .rel* and .dyn* into .rodata, and this
made ld to generate the wrong size for .rela* sections that covered
other unrelated sections. When the EFI image was loaded, _relocate()
went through the unexpected data and may cause unexpected crash.
This commit moves .rel* and .dyn* out of .rodata in the ld script but
also moves the related variables, such as _evrodata, _rodata_size,
and _rodata_vsize, to the end of the new .dyn section, so that the
crafted pe-coff section header for .rodata still covers our new
.rela and .dyn sections.
(*) 212ba30544f ("arm/aa64 targets: put .rel* and .dyn* in .rodata")
Fix issue: https://github.com/rhboot/shim/issues/371

arm/aa64: fix the size of .rela* sections

---

mok.c

Fix the case where data_size is 0, so config_template is
not implicitly copied like the size calculation above.
upstream-status: https://github.com/rhboot/shim/issues/249
Signed-off-by: Jonathan Yong <jonathan.yong@intel.com>

mok: fix potential buffer overrun in import_mok_state

---

mok.c

Some UEFI environment such as u-boot doesn't implement
QueryVariableInfo(), so we couldn't rely on the function to estimate the
available space for RT variables. All we can do is to call SetVariable()
directly and check the return value of SetVariable().

mok: relax the maximum variable size check

---

replacements.c

When EBS protection is disabled unhook_system_services() still
"restores" EBS in the boot services table. However, EBS was not
replaced and the original value not saved, so NULL is written. Then
when the OS tries to call EBS it ends up jumping to NULL.
Fix this by also compiling out the code to unhook EBS when
DISABLE_EBS_PROTECTION is defined.
Fixes: 4b0a61dc9a95 ("shim: compile time option to bypass the ExitBootServices() check")
Signed-off-by: Seth Forshee <seth.forshee@canonical.com>

Don't unhook ExitBootServices when EBS protection is disabled

---

fallback.c

The CopyMem() calls in add_to_boot_list() expect that
find_boot_option() returned an index to the matching entry in the
BootOrder array. The previous code returned the numerical portion of
the boot entry label, which in some cases resulted in -1 *
sizeof(CHAR16) being passed to CopyMem() which would in turn corrupt
the running firmware resulting in an exception and a failure to boot
or reset.

fallback: find_boot_option() needs to return the index for the boot entry in optnum

---

httpboot.c

Some servers (HAProxy) yield Content-Length in lowercase, and shim would
fail to find it.
Signed-off-by: Robbie Harwood <rharwood@redhat.com>

httpboot: Ignore case when checking HTTP headers

---

fallback.c

This fixes two bugs with fallback's read_file() allocation.

Fallback allocation errors

---

shim.c

An error message complaining about missing file BOOTx64.EFI makes no
sense on other architectures.

shim: avoid BOOTx64.EFI in message on other architectures

---

include/str.h

There is no need to check the parameters of strntoken() twice.
Fixes: c7bb10cf154a ("Tidy up our string primitives...")

str: remove duplicate parameter check

---

Makefile
fallback.c

In the cloud, all boots are non-interactive with keyboard and console
access either typically not available or prohibited. Also clouds
always do firstboot via fallback. This currently results in an
unacceptable 5s boot delay whilst fallback offers interactive reset
options that cannot be actioned.
In Ubuntu, we'd like to make fallback noninteractive by default
without any boot delays, due to bootspeed impact on firstboot of the
preinstalled images.
Bug-Ubuntu: https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1922581
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

fallback: add compile option FALLBACK_NONINTERACTIVE

---

SBAT.md

Signed-off-by: Esther Shimanovich eshimanovich@google.com
I've had a bit of trouble understanding SBAT.md, so I thought I might open up a PR with a few additions that might help with readability, and some questions. Hopefully this might be helpful to other people as well.
1) Can you define disclosure (from the chart included in the file)?
2) Where do the numbers 5 and 6 in the chart come from? I expected the fields under "after Vendor C's first Update" to be 2 and 3 instead of 5 and 6. Why the big jump from 1 to 5?
3) Why do you need both upstream's version of grub and downstream's version of grub in the sbat.csv file? Isn't only one used?
4) Will the product specific generation number continually increase for each global or do they reset? I was a little confused by this sentence: "The …

Modify sbat.md to help with readability.

---

csv.c
test-csv.c

.sbat sections contain user supplied data. We should not assume that it is
well formed. The last line feed might be missing or it might not be at the 
end of the file. Instead one or more \0 might follow.
In parse_csv_data() variable 'line' is a pointer with a value between
the values of 'data' and 'data_end'.
There is no reason to check that it is non-zero after assigning it
from 'data' as we already check 'data'.
Instead at the beginning of the file and after each line we must check that
we have not reached the end of the file marked by a '\0' character.

csv: detect end of csv file correctly

---

SBAT.md

The SBAT variable is defined as ASCII, but the SBAT section in a binary was defined as UTF-8. These should match.
Use ASCII rather than UTF-8, because naive parsing of UTF-8 could lead to unexpected results. For example the character 'ä' can be encoded as 0xe4 or as 0x61 0x0308, and these should be considered equivalent. The shim is not smart enough to do this. This could lead to missed verifications, if the variable and section use different encodings.
Define everything as ASCII. It's sad not to be able to have 🦀 in our bootloader names, and potentially annoying for vendor names as well, but oh well.

Specify that the .sbat section is ASCII not UTF-8

---

include/test.mk

On Arch Linux, the GCC version of `limits.h` is in the `include-fixed` instead of the `include` directory. It needs to be included in the include directories list, otherwise attempting to compile the test suite fails with the following error:
```
In file included from /usr/include/efivar/efivar-dp.h:22,
from /usr/include/efivar/efivar.h:238,
from include/test.h:51,
from shim.h:68,
from csv.c:6:
/usr/include/limits.h:124:16: fatal error: limits.h: No such file or directory
124 | # include_next <limits.h>
|                ^~~~~~~~~~
compilation terminated.
```

tests: add "include-fixed" GCC directory to include directories

---

include/pe.h
pe.c

Copying the value of datasize_in to two further variables and then using
all three randomly in the code makes it hard to read.
datasize_in is never changed in generate_hash() so we can do with this
parameter alone. Let's declare it as const to verify that its value
is invariant.

pe: simplify generate_hash()

---

tpm.c

On Dell hardware booted in UEFI with option TPM 1.2 "On without Pre-Boot
Measurements", it appears that `tpm_log_event()` fails with Unsupported,
which causes Shim to abort due to believing it couldn't set up the
MokListRT, MokListXRT and SbatLevelRT variables.
This patch mimics what is done in Grub code: just ignore failures
related to the TPM.
Below is the verbose output of Shim.
1. With original code
~~~
mok.c:358:mirror_mok_db() SetVariable("MokListRT", ... varsz=0x826) = Success^M
mok.c:792:mirror_one_mok_variable() mirror_mok_db("MokListRT",  datasz=2086) returned Success^M
mok.c:823:mirror_one_mok_variable() tpm_log_event(0x5C506020, 2086, 14, "MokList")->Unsupported^M
Could not create MokListRT: Unsupported^M
mok.c:940:import_one_mok_state() returning Unsupported^M
[... same for …

Don't make shim abort when TPM log event fails (RHBZ #2002265)

---

MokManager.c
include/console.h
lib/console.c

There's a potential for future (or even existing) platforms to without console output to not populate ST->ConIn and ST->ConOut.  This patch set adds checks to all of our usage of those protocol shortcuts.

Better console checks

---

SBAT.example.md

The name of the SBAT UEFI variable changed from "SBAT" to "SbatLevel" in
27da4170f0fb30acde91a37e0256dfcfe76ea69e. Update the documentation to match.
Signed-off-by: Nicholas Bishop <nicholasbishop@google.com>

docs: update SBAT UEFI variable name

---

fallback.c

The buffer used to read the data in the CSV is declared as a stack variable
in the try_boot_csv() function, but a pointer to the arguments field of the
first boot option is stored in the global first_new_option_args variable.
Later, when is used set the arguments to boot the first entry, the variable
points to memory that no longer exists. This leads to booting an entry with
garbage as arguments instead of the correct value.
Reported-by: Alexander Larsson <alexl@redhat.com>
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

fallback: fix fallback not passing arguments of the first boot option

---

shim.c

Requesting a keystroke when Secure Boot is not enabled and verbosity is enabled is really annoying.

shim: Don't stop forever at "Secure Boot not enabled" notification

---

MokManager.c
fallback.c
include/hexdump.h
include/system/stdarg.h
lib/variables.c
mok.c

I've fixed stuff that coverity found that's not in Cryptlib/ or gnu-efi/

Shim 15.5 coverity

---

pe.c

perror(L"%d sections contain entry point\n") lacks an argument
corresponding to %d.

pe: missing perror argument

---

lib/console.c

On some platform, like GCP or OVMF which does NOT provide
EFI_GRAPHICS_OUTPUT_PROTOCOL when no display device (or the display device
be disabled). It causes that the "Error: Locate graphic output protocol
fail: (0xE) Not Found." always be showed on console when we enroll MOK
through MokManager. The message box blocked the process of enrolling
MOK and scared user. The error message is introduced by 55163bc82c517 since
15.2. This patch removed the error message.
https://github.com/rhboot/shim/issues/440

MokManager: removed Locate graphic output protocol fail error message

---

include/pe.h
pe.c
shim.c

This implements SBAT verification via the shim_lock protocol
by moving verification inside the existing verify_buffer()
function that is shared by both shim_verify() and handle_image().
The .sbat section is optional for code verified via the shim_lock
protocol, unlike for code that is verified and executed directly
by shim. For executables that don't have a .sbat section,
verification is skipped when using the protocol.
A vendor can enforce SBAT verification for code verified via the
shim_lock protocol by revoking all pre-SBAT binaries via a dbx
update or by using vendor_dbx and then only signing binaries that
have a .sbat section from that point.

shim: implement SBAT verification for the shim_lock protocol

---

post-process-pe.c

With -Werror these were causing build failures with stricter gcc:
.../post-process-pe.c: In function 'load_pe':
.../post-process-pe.c:177:55: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
.../post-process-pe.c:192:56: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'UINT64' {aka 'long long unsigned int'} [-Werror=format=]
.../post-process-pe.c:236:31: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'UINT64' {aka 'long long unsigned int'} [-Werror=format=]
.../post-process-pe.c:39:32: note: in definition of macro 'debug'
.../post-process-pe.c:236:60: note: format string is defined here
.../post-process-pe.c:240:31: error: format '%zu' …

post-process-pe: Fix format string warnings on 32-bit platforms

---

include/test.mk

On Debian(-derived) systems low-level system headers are under
/usr/include/<multi-arch path>, so look there too.
Otherwise we see stuff like:
gcc -O2 -fno-diagnostics-color -ggdb -std=gnu11 -isystem <foo>/shim.git/include/system -I<foo>/shim.git/gnu-efi/inc -I<foo>/shim.git/gnu-efi/inc/ia32 -I<foo>/shim.git/gnu-efi/inc/protocol -Iinclude -iquote . -isystem /usr/include -isystem /usr/lib/gcc/i686-linux-gnu/11/include -mno-mmx -mno-sse -mno-red-zone -nostdinc -maccumulate-outgoing-args  -m32 -DMDE_CPU_IA32 -DPAGE_SIZE=4096   -fshort-wchar -fno-builtin -rdynamic -fno-inline -fno-eliminate-unused-debug-types -fno-eliminate-unused-debug-symbols -gpubnames -grecord-gcc-switches  -Wall -Wextra -Wno-missing-field-initializers -Wsign-compare -Wno-deprecated-declarations …

tests: also look for system headers in multi-arch directories

---

mock-variables.c
test-str.c

This PR fixes gcc warnings found when building the tests (also if FORTIFY_SOURCE enabled by default).
All tests passed with these changes.

tests: fix gcc warnings

---

MokManager.c
include/test-data-efivars-1.h
mok.c
test-mok-mirror.c

Within previous versions of shim the MokListTrusted var did not
exist.  Add the ability through a compile time option to set
the MokListTrustedRT when the BS var does not exist.  When
the BS var exists, MokListTrustedRT is not set.  This inverse
logic allows a distro to give the end-user the ability to opt
out of this feature instead of opting in.
Many Linux distros carry out of tree patches to trust the mok
keys by default.  These out of tree patches can be dropped
when compiling shim this way and using a Linux kernel that
supports MokListTrustedRT.
Signed-off-by: Eric Snowberg <eric.snowberg@oracle.com>

Allow MokListTrusted to be enabled by default

---

.gitmodules
Make.defaults
elf_aarch64_efi.lds

This patchset resurrects aarch64 support, using new objcopy options that are in binutils-2.38.  Note that the gnu-efi branch changes, and the shim-15.6 branch has several patches on it.

Re-add ARM AArch64 support

---

lib/console.c

This is https://github.com/rhboot/shim/pull/271 all over again, because I realized I shouldn't have pushed anything to rhboot/main until shim-15.5 is released.

Use ASCII as fallback if Unicode Box Drawing characters fail

---

BUILDING
fallback.c
lib/Makefile
lib/console.c
shim.c
shim.h

This makes SHIM_VERBOSE / SHIM_DEVEL_VERBOSE work the same way as
SHIM_DEBUG / SHIM_DEVEL_DEBUG when shim is built with ENABLE_SHIM_DEVEL
set.

shim: use SHIM_DEVEL_VERBOSE when built in devel mode

---

sbat.c

Break out of the inner sbat loop if we find the entry.

---

globals.c
include/mok.h
include/pe.h
mok.c
pe.c
shim.c
shim.h

Please see the following as an RFC pull request for loading additional certificates from a signed EFI binary.  
This work was originally done by @mjg59, I have ported parts of his code to 15.5 and refactored other pieces.   https://github.com/rhboot/shim/pull/204
All testing was done using certmule (https://github.com/rhboot/certmule).

Support loading additional certificates

---

sbat.c
test-sbat.c

preserve_sbat_uefi_variable() shoud really deal with the sbat
metadata version as a numerical value that could gain more digits.
It also needs to only compare the datestamp since the actual
metadata can grow and shrink
Signed-off-by: Jan Setje-Eilers <Jan.SetjeEilers@oracle.com>

Fix preserve_sbat_uefi_variable() logic

---

shim.c

When calling back into shim from grub, the MokListRT may contain additional
entries not available in the original MokList, an example being the certs
included via user_cert. Use the MokListRT instead when calling check_db_cert
and check_db_hash.
Signed-off-by: Eric Snowberg <eric.snowberg@oracle.com>

Reference MokListRT instead of MokList

---

README.md

It's been suggested that we should link to the test plan in the readme.
This seems pretty reasonable to me, so here it is.

Add a link to the test plan in the readme.

---

include/ucs2.h
load-options.c

In 6c8d08c0af4768c715b79c8ec25141d56e34f8b4 ("shim: Ignore UEFI
LoadOptions that are just NUL characters."), a check was added to
discard load options that are entirely NUL.  We now see some firmwares
that start LoadOptions with a NUL, and then follow it with garbage (path
to directory containing loaders).  Widen the check to just discard
anything that starts with a NUL.
Resolves: #490
Related: #95
See-also: https://bugzilla.redhat.com/show_bug.cgi?id=2113005
Signed-off-by: Robbie Harwood <rharwood@redhat.com>

Discard load-options that start with a NUL

---

Make.defaults

This changes the alignment of UINT64 data to 8 bytes on IA32, which matches EDK2's understanding of alignment. In particular this change affects the offset where shim writes `EFI_LOADED_IMAGE.ImageSize`.
Fixes https://github.com/rhboot/shim/issues/515
Signed-off-by: Nicholas Bishop <nicholasbishop@google.com>

Add -malign-double to IA32 compiler flags

---

pe.c

Seen mokmanager image load failure '2 sections contain entry point' for shim built on Oracle Linux 9 aarch64. found_entry_point counter in handle_image() uses SizeOfRawData to calculate section boundary. PE spec defines VirtualSize for the total size of the section when loaded into memory. SizeOfRawData is the size of the section (for object files) or the size of the initialized data on disk.
Fix this issue by updating section in-memory size limit to VirtualSize.
Resolves: #517
Signed-off-by: Ilya Okomin <ilya.okomin@oracle.com>

pe: Fix image section entry-point validation

---

make-archive

Remove timestamps, user names, etc. from the tarball so that it can be built reproducibly by multiple people, on different machines.
The outer bzip2 layer might still be different, no reproducible bzip2 known.
This sets the time to 0, it would also be possible to set it to the git tag time.

make-archive: Build reproducible tarball

---

mok.c

MokListTrusted was added by mistake to PCR 7 in 4e513405. The value of MokListTrusted does not alter the behavior of secure boot so, as per https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClient_PFP_r1p05_v23_pub.pdf#page=36 (section 3.3.4 PCR usage) so it should not be factored in the value of PCR 7.
See:
https://github.com/rhboot/shim/pull/423
https://github.com/rhboot/shim/commit/4e513405b4f1641710115780d19dcec130c5208f
Fixes https://github.com/rhboot/shim/issues/484
Fixes https://github.com/rhboot/shim/issues/492

mok: remove MokListTrusted from PCR 7

---

Makefile
data/sbat.csv
include/sbat_var_defs.h
model.c

Final changes for shim-15.7 (not including tagging)
- bump grub's required SBAT_LEVEL version
- bump shim's .sbat version
- minor coverity related changes

Shim 15.7 version update

---

include/test.mk
sbat_var.S
test-sbat.c

In https://github.com/rhboot/shim/issues/533 , iokomin noticed that gas in binutils before 2.36 appears to be incorrectly concatenating string literals in '.asciz' directives, including an extra NUL character in between the strings, and this will cause us to incorrectly parse the .sbatlevel section in shim binaries.
This patch adds test cases that will cause the build to fail if this has happened, as well as changing sbat_var.S to to use '.ascii' and '.byte' to construct the data, rather than using '.asciz'.

Make sbat_var.S parse right with buggy gcc/binutils

---

Cryptlib/SysCall/BaseMemAllocation.c

There is one long-standing problem in CRT realloc wrapper, which will cause the obvious buffer overflow issue when re-allocating one bigger memory block:
void *realloc (void *ptr, size_t size)
{
//
// BUG: hardcode OldSize == size! We have no any knowledge about
// memory size of original pointer ptr.
//
return ReallocatePool ((UINTN) size, (UINTN) size, ptr);
}
This patch introduces one extra header to record the memory buffer size information when allocating memory block from malloc routine, and re-wrap the realloc() and free() routines to remove this BUG.
Cc: Laszlo Ersek <lersek@redhat.com>
Cc: Ting Ye <ting.ye@intel.com>
Cc: Jian J Wang <jian.j.wang@intel.com>
Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: Qin Long <qin.long@intel.com>
Reviewed-by: Jian J Wang …

CryptoPkg/BaseCryptLib: Fix buffer overflow issue in realloc wrapper

---

pe.c

Setting memory attributes is generally done at page granularity, and this is enforced by checks in `get_mem_attrs` and
`update_mem_attrs`. But unlike the section address, the section size isn't necessarily aligned to 4KiB. Round up the section size to fix this.
Signed-off-by: Nicholas Bishop <nicholasbishop@google.com>

pe: Align section size up to page size for mem attrs

---

shim.c

On DELL R350 booting DVD through RFS with BIOS 1.4.2 in Secure Boot, firmware returns *EFI_BUFFER_TOO_SMALL* but with new *buffersize* set to 0, which causes the `load_certs()` code to loop forever:
~~~
while (1) {
efi_status = dir->Read(dir, &buffersize, buffer);
if (efi_status == EFI_BUFFER_TOO_SMALL) {
...
continue;
}
...
}
~~~
This commit prevents such infinite loop. The new code doesn't check if new *buffersize* is 0 only, but if it's different from *old* one we passed, which may cover more buggy firmware cases at minor cost.

Don't loop forever in load_certs() with buggy firmware

---

shim.c

These calls did not check the return value. If they had, it would have shown that the calls were failing due to passing `NULL` for the `realloc` function pointer. That [causes an early return](https://github.com/rhboot/shim/blob/main/Cryptlib/OpenSSL/crypto/mem.c#L157), so the calls weren't actually doing anything.
The `malloc`/`realloc`/`free` functions defined in [Cryptlib/SysCall/BaseMemAllocation.c](https://github.com/rhboot/shim/blob/main/Cryptlib/SysCall/BaseMemAllocation.c) are what actually get used, so just drop the explicit call to `CRYPTO_set_mem_functions`.

Drop invalid calls to `CRYPTO_set_mem_functions`

---

test-sbat.c

Fix the `main` function in `test-sbat.c` to return the `status` variable like the other `test-*.c` files.
Signed-off-by: Nicholas Bishop <nicholasbishop@google.com>

test-sbat: Fix exit code

---

include/sbat_var_defs.h

(See https://bugs.debian.org/1024617)
One of the Debian builds of grub bumped the SBAT to 3, but didn't include the patches needed. Add "grub.debian,4" to block those binaries.
Signed-off-by: Steve McIntyre <steve@einval.com>

Block Debian grub binaries with SBAT < 4

---

SBAT.example.md
SBAT.md

- A rendering error which caused the `<Vendor>_key.EFI` text to be rendered as `_key.EFI` has been fixed
- Two misspellings have been fixed
- Tables have been reformatted to be more readable as plaintext. Rendering remains the same.

SBAT-related documents formatting and spelling

---

SbatLevel_Variable.txt

This serves to document the SbatLevel Boot Services variable so that other boot services code, such as bootmgr can update the revocation level.
We did not do the best job documenting these CVE lists in the past, hopefully this file will fix that as well. Reviews of the lists in particular would be appreciated.

Add SbatLevel_Variable.txt to document the various revocations

---

Cryptlib/Makefile
Cryptlib/OpenSSL/Makefile

Cryptlib and OpenSSL both currently throw warnings with some compilers using -Wunused-but-set-variable:
clang -std=gnu11 -ggdb -ffreestanding -fmacro-prefix-map=/home/pjones/devel/github.com/shim/main/= -fno-stack-protector -fno-strict-aliasing -fpic -fshort-wchar -nostdinc -m64 -mno-mmx -mno-sse -mno-red-zone  -Os -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Werror -I/home/pjones/devel/github.com/shim/main/Cryptlib -I/home/pjones/devel/github.com/shim/main/Cryptlib/Include -I/home/pjones/devel/github.com/shim/main/gnu-efi/inc -I/home/pjones/devel/github.com/shim/main/gnu-efi/inc/x86_64 -I/home/pjones/devel/github.com/shim/main/gnu-efi/inc/protocol -isystem /home/pjones/devel/github.com/shim/main/include/system -isystem /usr/lib64/clang/16/include -DMDE_CPU_X64 …

Use -Wno-unused-but-set-variable for Cryptlib and OpenSSL

---

.gitignore
Makefile
cert.S
include/console.h
sbat_var.S

This is a small collection of minor changes:
- make rules to generate compile_commands.json, which is used by some editors for real-time error checking
- add gnu-stack notes to all our .S files, which reduces pointless compiler warnings
- minor modifications to dprintf() to support some test cases to be introduced later.

Minor housekeeping

---

shim.c

Verifying the validity of a files signature can protect from an attacker creating a file that exploits a pontential issue in the sbat validation. If the singature is not checked first, an attacker can just create a file with a valid .sbat section and can still attack the signature valiation.

Verify signature before verifying sbat levels

---

.gitignore
Makefile
fuzz-csv.c
fuzz-sbat.c
include/fuzz.mk
sbat.c
test-sbat.c

shim takes several forms of input from several sources that are not necessarily trustworthy.  As such, we need to take measures to validate that we don't have unacceptable results from bad inputs.  One such measure is "fuzzing" the inputs which parse untrusted data by running them with randomized or partially randomized input.
This change adds such testing using clang's "libFuzzer" to our CSV parser and the parser for `.sbat` sections.

Add libFuzzer support for csv.c and sbat.c

---

pe-relocate.c

```context->RelocDir->Size``` should minus one when calling ```ImageAddress()```. Otherwise
**RelocBaseEnd** will get NULL address after running ImageAddress() in which ```address=size```.
```
ImageAddress (void *image, uint64_t size, uint64_t address)
{
uintptr_t img_addr;
/* ensure our local pointer isn't bigger than our size */
if (address >= size)   <---- address=size
return NULL;
........
}
```
```RelocBaseEnd = ImageAddress(orig, size, Section->PointerToRawData + context->RelocDir->Size);```

Size should minus 1 when calculating 'RelocBaseEnd'

---

mok.c

The code that mirrors MOK database to EFI variables gets the remaining variable storage size from the firmware and subtracts the size needed for any overhead to see if there is enough space to create a new entry.
However these calculations are on unsigned integer types, they can underflow and result in huge values when the firmware is about to run out of usable variable space. Explicitly check against this.

mok: Avoid underflow in maximum variable size calculation

---

Make.rules
Makefile
include/fanalyzer.mk
include/scan-build.mk

These are a couple of housekeeping fixes that help with "scan-build", "gcc -fanalyze", etc.

Housekeeping

---

mok.c

On some ARM platform, jlinton noticed that when we fail to set a variable (because it isn't supported at all, presumably), our error message has an extra argument that doesn't match the format string.
This patch removes the extra argument.

mok: fix LogError() invocation

---

Makefile

If we see "BEGIN CERTIFICATE", it's a PEM certificate and won't work. Fail the build early and say so.
Fixes #645

Validate that a supplied vendor cert is not in PEM format

---

include/sbat_var_defs.h

Add the previous latest level to the switch for automatic.

sbat: Add grub.peimage,2 to latest (CVE-2024-2312)

---

include/sbat_var_defs.h

Back in January we decided to bump the SBAT level for the shim
CVE without bumping the grub level for the previous NTFS issues
- CVE-2023-4692 CVE-2023-4693 - as not every vendor was signing
the ntfs module.
Catch up on this revocation to ensure it doesn't get lost. Doing
so also allows us to remove the grub.debian,4 revocation as this
happened before grub,4 and hence is obsolete.
Also bump the date of the sbat variable to today's. Don't copy
the April 5 one to a previous selection, as it wasn't shipped
to anyone.

sbat: Also bump latest for grub,4 (and to todays date)

---

shim.c

In the ea0f9df "Allow SbatLevel data from external binary" patch the code that tries to load any certificate file that starts with shim_certificate was changed to only accept shim_certificate.efi which defeats the entire point of reading through the directory. This change reverts that.

undo change that limits certificate files to a single file

---

load-options.c

When LoadOptions is either L" " or L"shim.efi ", parse_load_options sets second_stage to the empty string. This is unlikely to be what is intended, and typically leads to a non-obvious failure mode.
The failure happens because parse_load_options's call to split_load_options (after eating shim's own filename, if present) returns the empty string. Since init_grub typically passes second_stage to start_image, this causes read_image to concatenate the empty string onto the directory name. This means PathName refers to the directory, not the path to a pe image. Then load_image successfully opens a handle on the directory and reads "data" from it. It only eventually fails when handle_image calls read_header which finds that this data isn't in fact a pe header, reporting "Invalid image".
This …

shim: don't set second_stage to the empty string

---

make-certs

If there is no OpenSSL installation on the system, where the `make-certs` script is run at, no error message will be shown; instead the script will fail silently and no certificates will be generated.
This change introduces a simple check, if the `openssl` binary is present and informs the user, if it's missing, shortening debugging time from minutes to mere seconds.
A bashism has been used so a pretty message gets printed without moving the check to a section before `set -e`.

make-certs: Handle missing OpenSSL installation

---

Make.defaults

export DEFINES for sub makefile

---

shim.c

The code actually uses EFI_SECURE_BOOT_DB_GUID which is defined in include/guid.h, drop the unused EFI_IMAGE_SECURITY_DATABASE_GUID define from shim.c

Drop unused EFI_IMAGE_SECURITY_DATABASE_GUID definition

---

fallback.c

In case CSV entry contains boot argument (e.g. an image to load for shim) it must be null-terminated. While populate_stanza() makes sure 'arguments' end with '\0', add_boot_option() doesn't account for it in 'size' calculations. E.g. for the following CSV entry:
```
shimx64.efi,6.6.0-0.rc0.20230904git708283abf896.6.fc40.x86_64,\EFI\Linux\5f93b3c9cf1c488a99786fb8e99fb840-6.6.0-0.rc0.20230904git708283abf896.6.fc40.x86_64.efi,Comment
```
the resulting variable after 'fallback' looks like:
```
0000180 0038 0036 005f 0036 0034 002e 0065 0066
0000190 0069
0000192
```
Add trailing '\0' to 'size' calculations in add_boot_option() when 'arguments' is not empty. The resulting variable looks like:
```
0000180 0038 0036 005f 0036 0034 002e 0065 0066
0000190 0069 0000
0000194
```
and the specified …

Null-terminate 'arguments' in fallback

---

Make.defaults

Addresses #606.
I am not sure if the location where I have added the flags is ideal, though it does make shim debuggable again.

Force gcc to produce DWARF4 so that gdb can use it

---

.github/workflows/pullrequest.yml
Cryptlib/Makefile
Cryptlib/OpenSSL/Makefile
Makefile
include/compiler.h

This fixes a header error with clang, and suppresses the clang compiler warnings when building `compile_commands.json`

Minor housekeeping 2024121700

---

load-options.c

Windows bcdedit.exe creates boot entries where load options begin with "WINDOWS\0" (in 8-bit chars), followed by some Windows-specific data which is useless for shim. This data causes shim error "Failed to open \EFI\mypath\䥗䑎坏S".
Resolves: #370

Discard load-options that start with WINDOWS

---

shim.c

The interface shouldn't be replaced at the shim_fini
stage When the vendor certificate doesn't exist.

Fix the issue that the gBS->LoadImage pointer was empty.

---

.gitmodules

This updates our gnu-efi module to include the UEFI 2.10 error codes.

Update gnu-efi submodule for EFI_HTTP_ERROR

---

Makefile

Although file alignment for EFI apps is not clear, most of the UEFI accept defaulf file alignment (0x200). Nevertheless some of the buggy UEFI bootloaders require file alignment to be 0x1000 (e.g. Lenovo Miix 630, Lenovo Yoga C630, etc). There is no way to fix those machines as they are EOL. Increase file alignment to the desired value.
Fixes #670

Increase EFI file alignment

---

sbat.c

In original sbat.c:
```
else if (preserve_sbat_uefi_variable(sbat, sbatsize, attributes,
sbat_var_candidate) &&
!reset_sbat) {
```
The time omplexity of preserve_sbat_uefi_variable() is higher than reset_sbat. Maybe we could swap both of them to calculate reset_sbat first. Such that the shortcut performance can be improved.

Improve shortcut performance when comparing two boolean expressions

---

Makefile
dp.c
include/dp.h
mok.c
shim.c
shim.h

If MokManager has to be entered but system is booting on disk on `EFI/BOOT/BOOTx.EFI` entry, MokManager cannot be found because it's not in that directory.
This indicates an issue with the BootOrder or the UEFI firmware is just not taking BootOrder into account (seen on Lenovo ThinkPad P1 Gen 6 and VMWare).
This patch prints a related message and reboots after 10 seconds.
1. Import a certificate using mokutil
2. Tell UEFI to boot on BOOTX64.EFI entry on next boot
~~~
mok.c:1045:import_mok_state() checking mok request
shim.c:866:load_image() attempting to load \EFI\BOOT\mmx64.efi
Failed to open \EFI\BOOT\mmx64.efi - Not Found
Failed to load image 貘給: Not Found
shim.c:888 load_image() Failed to open \EFI\BOOT\mmx64.efi - Not Found
shim.c:1115 read_image() Failed to load image 貘給: Not Found …

Provide better error message when MokManager is not found

---

MokManager.c

CertList->SignatureSize is of type UINT32 which is always positive.
If CertList->SignatureListSize == 0, then
CertList->SignatureListSize <= CertList->SignatureSize
is also true.
Remove the redundant CertList->SignatureListSize == 0 checks.
A message "Corrupted signature list" is better suited then
"Invalid MOK detected! Ignoring MOK List." in this case.

MokManager: remove redundant logical constraints

---

include/mock-variables.h
mock-variables.c
test-mok-mirror.c

This patch set adds `test_mok_mirror_1()`, which is basically like `test_mok_mirror_0()` except with a variable size limit smaller than `MokListRT` would be, and with the `.must_be_absent` flag set to `true` in the test data, so the test will fail if the variable is successfully created *or* if the data is not in the mokvars config variable.

Test import_mok_state() when MokListRT would be bigger than available size

---

include/mock-variables.h
test-mok-mirror.c

In 70366a286552760863bacb521fb00c654586b494, I introduced a test case for test-mok-mirror to test the behavior when SetVariable() gives EFI_OUT_OF_RESOURCES.  Unfortunately this includes a memory error in its cleanup functions:
==1972634== Invalid read of size 8
==1972634==    at 0x4032F3: mock_sv_adjust_usage_data (mock-variables.c:468)
==1972634==    by 0x40387B: mock_delete_variable (mock-variables.c:541)
==1972634==    by 0x4014E8: mock_reset_variables (mock-variables.c:1353)
==1972634==    by 0x401348: mock_finalize_vars_and_configs (mock-variables.c:1405)
==1972634==    by 0x401731: main (test-mok-mirror.c:688)
==1972634==  Address 0x1ffeffc4f8 is on thread 1's stack
==1972634==  6784 bytes below stack pointer
This is caused because the test data uses a linked-list data structure in …

test-mok-mirror: minor bug fix

---

lib/simple_file.c

The loop retrieving the SimpleFS volume labels and names may skip some volumes if either HandleProtocol or OpenVolume or GetInfo fails. Those skipped volumes would have uninitialized pointers to their names in the respective entries indices. This would lead to accessing random memory in console_select, because count_lines would not catch the holes with non-existing entries.
On affected platforms the result is a hang of the MokManager while trying to enroll a key from disk. The issue has been triggered on a TianoCore EDK2 UEFIPayload based firmware for x86 platforms with additional filesystem drivers: ExFAT, NTFS, EXT2 and EXT4.

Fix file system browser hang when enrolling MOK from disk

---

shim.c

This just turns off the clang-tidy warning about our SBAT_VAR_NAME string compositing in the error message list in efi_main(), as it's the only warning in the whole file and it's bugging me.

Ignore a minor clang-tidy nit

---

shim.c

Only certain errors trigger fallback to the default loader name.  This change allows fallback when encountering `EFI_TFTP_ERROR` as well.  And ideally would also handle `EFI_HTTP_ERROR` the same way, but that requires updating gnu-efi to a version newer than the shim-15.8 branch.
This fixes the issue reported in https://github.com/rhboot/shim/issues/649 that prevents boot on some models of PC.

Allow fallback to default loader when encountering errors on network boot

---

include/test.mk

Sometimes using a temp file to make test-random.h breaks builds because clean and test get made in parallel.
Since debugging parallel make is anything but easy, it's better to just not use the intermediate file.  This patch makes it use a pipe instead.

test.mk: don't use a temporary random.bin

---

pe.c

When memory attributes cannot be updated due to misalignment with 4K or when the size is 0, the debug printout lacks sufficient clarity to indicate the issue. To enhance troubleshooting, it is crucial to generate an error log that explicitly states the failure to execute the expected action. This error log will be visible even when the debug level log is not enabled, thereby significantly reducing debugging time.

pe: Enhance debug report for update_mem_attrs

---

shim.c

A couple of improvements for performing verification with multiple certificates.

Multiple certificate handling improvements

---

.gitignore
Makefile
SbatLevel_Variable.txt
generate_sbat_var_defs.c
include/sbat_var_defs.h
sbat_var.S
test-sbat.c

This makes SbatLevel_Variable.txt the single source of truth for SbatLevel metadata and generates the header file from it.

Generate SbatLevel Metadata from SbatLevel_Variable.txt

---

BUILDING
Cryptlib/InternalCryptLib.h
Cryptlib/Library/BaseCryptLib.h
Cryptlib/Makefile
Cryptlib/Pk/CryptPkcs7Verify.c
Cryptlib/Pk/CryptPkcs7VerifyEku.c

Implement the CodeSign EKU check to fulfill the requirements of NIAP OS_PP.
Also modify the ModSign EKU check to use VerifyEKUsInPkcs7Signature() to
check the signer certificate instead of the certificate directly from the
key database.
These commits supersede the PR#232 and PR#661 (Apply the EKU checks) and
separate the original author's codes from other commit so that the author's
original codes can be quite independent.
The author also answered the question in PR#232 and  changed the conditional
statement to EFI_Status != EFI_SUCCESS right after VerifyEKUsInPkcs7Signature()
in Cryptlib/Pk/CryptPkcs7Verify.c
User can optionally enable codesign EKU check in compiling time.
To enable the codesign check, set ENABLE_CODESIGN_EKU to 1.
To disable the codesign check, set ENABLE_CODESIGN_EKU …

Apply EKU check with compile option

---

Delivering_Sbat_Revocations.md

Revocation metadata has been consolidated into SbatLevel_Variable.txt and can be delivered both built into shim as well as via revocations_sbat.efi binaries. This adds a short text file describing how revocation levels can be built into these components and delivered.
This depends on:
https://github.com/rhboot/shim/pull/711
https://github.com/rhboot/shim/pull/686
https://github.com/rhboot/certwrapper/pull/12

Document how revocations can be delivered

---

mok.c

The CopyMem() introduced in
ad8692e avoid EFIv2 runtime services on Apple x86 machines copies 100 CHAR16s no matter what. NX enabled firmware catches this and the boot breaks on those systems.
https://uefi.org/specs/UEFI/2.10/04_EFI_System_Table.html says that FirmwareVendor is a pointer to a null terminated string that identifies the vendor that produces the system firmware for the platform. If we can rely on it being null terminated then we don't need to copy the string at all.

regression: CopyMem() in ad8692e copies out of bounds

---

errlog.c
include/compiler.h
include/console.h
include/errlog.h
load-options.c
shim.c
shim.h

This changes our debug and error logging to save the entire logs into mok-variables as "shim-dbg.txt" and "shim-log.txt".

Save the debug and error logs in mok-variables

---

README.tpm

README.tpm incorrectly stated that  vendor_db is logged as "db" when in fact it logs as "vendor_db". This caused confusion like
https://github.com/keylime/keylime/issues/1725
Fixing the code risks breaking existing logs, so we're updating the doc instead. vendor_dbx is in fact logged as "dbx", so that remains unchanged.
Thanks to Morten Linderud <morten@linderud.pw> for raising this.

README.tpm: reflect that vendor_db is in fact logged as "vendor_db"

---

httpboot.c

If multiple headers occur, usually the last header would have authority; however the section [3.3.2](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2) of [RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230) states that:
>If a message is received that has multiple Content-Length header fields with field-values consisting of the same decimal value, ....., then the recipient MUST either reject the message as invalid.

Reject HTTP message with duplicate Content-Length header fields

---

errlog.c
globals.c
include/mok.h
mok.c
shim.c

It doesn't work reliably yet, and when it breaks it kills mok-variables along with it, so for now disable it.

Disable log saving

---

fallback.c

In issues #554 and elsewhere, it's been noted that when fallback is creating multiple entries, it will create them in one order and add them to BootOrder in the opposite order.  This is weird.
This patch changes fallback to keep a list of "new" entries, and then prepend that entire list to BootOrder when it's done, rather than prepending one at a time, that avoiding the inversion.
Resolves issue #554.

fallback: don't add new boot order entries backwards

---

README.tpm

Commit 092c2b2bbed950727e41cf450b61c794881c33e7 switched to using MokListRT instead of MokList during PCR7 measurement. Updating the README to reflect the correct behaviour.

README.tpm: Update MokList entry to MokListRT

---

SbatLevel_Variable.txt
generate_sbat_var_defs.c

Moves the minimum GRUB SBAT Level to 5 in order to require fixes for the following GRUB CVEs:
CVE-2024-45774
CVE-2024-45775
CVE-2024-45776
CVE-2024-45777
CVE-2024-45778
CVE-2024-45779
CVE-2024-45780
CVE-2024-45781
CVE-2024-45782
CVE-2024-45783
CVE-2025-0622
CVE-2025-0624
CVE-2025-0677
CVE-2025-0678
CVE-2025-0684
CVE-2025-0685
CVE-2025-0686
CVE-2025-0689
CVE-2025-0690
CVE-2025-1118
CVE-2025-1125

SBAT Level update for February 2025 GRUB CVEs

---

loader-proto.c

ardb noted in a comment on PR 656 that his code for shim_start_image() has the protocols and guids mismatched when we're uninstalling the protocol after the image has exited.
This fixes those to be paired correctly.

shim_start_image(): fix guid/handle pairing when uninstalling protocols

---

netboot.c

In case the ipv6 is not in a compressed format, the last chunk gets set to 0 because the str2ns() never executes.
As an example, without this fix provided, str2ip6 works correctly on a compressed address like 
2400:dd00::1 -> 24 00 dd 00 00 00 00 00 00 00 00 00 00 00 00 01
but fails on
2400:dd00:1234:1234:1234:1234:1234:1234 -> 24 00 dd 00 12 34 12 34 12 34 12 34 12 34  00 00
The fixed routine returns 24 00 dd 00 12 34 12 34 12 34 12 34 12 34 12 34 as expected.

Fix uncompressed ipv6 netboot

---

mock-variables.c
test-mock-variables.c

while preparing shim 16.0 for our Debian Bookworm based Debian derivative, I noticed the `test_get_variable_0` and `test_gnvn_0` tests failing (depending on SHIM_DEBUG value).
taking a closer look with gdb breaking at `test-mock-variables.c:310` for the `test_get_variable_0` case:
```
running test_install_config_table_0
test_install_config_table_0: passed
running test_get_variable_0
Breakpoint 1, test_get_variable_0 () at test-mock-variables.c:310
310             for (size_t i = 0; i < n_mok_state_variables; i++) {
(gdb) print mok_rt_vars
$1 = {0x7ffff7f6e9e0 <_IO_helper_jumps> "", 0x7ffff7f73760 <_IO_2_1_stdout_> "\207(\255", <incomplete sequence \373>, 0x0, 0x0, 0x0, 0x20676e696e6e7572 <error: Cannot access memory at address 0x20676e696e6e7572>,
0x7465675f74736574 <error: Cannot access …
```

fix test segfaults caused by uninitialized memory

---

generate_sbat_var_defs.c

In generate_sbat_var_defs.c, realloc() should allocate one more byte for the end of string '\0' when running sprintf() later. please also refer https://github.com/rhboot/shim/issues/744
Suppose we use fgets() to get line="abc\n", so strlen(line)=4 bytes. realloc(...,strlen(line),1) will allocate only 5 bytes which is not capable to save line(3 bytes),'\\' and 'n'(2 bytes) pluses extra '\0' byte totally 6 bytes when running sprintf(.....,"%s\\\n", line) later on. 
where '\n' of line has been removed in line[strlen(line) - 1] = 0;

Realloc() needs to allocate one more byte for sprintf()
